### ISSUE TITLE
alpha roadmap

### ISSUE THREAD

**Issue by wntkys** [wntkys/Podsolnuh-X#1]
- [ ] procedural terrain generation
- [ ] procedural terrain texturing

procedural units:
- [ ] command unit
- [ ] tank
- [ ] airplane
- [ ] ship

- [ ] multiplayer

Misc:

- [ ] frustum culling for terrain
- [ ] frustum culling for units
- [ ] music
